// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rento.Infrastructure.Implemenation.Db;

#nullable disable

namespace Rento.Migrations
{
    [DbContext(typeof(RentoDbContext))]
    [Migration("20250705061045_All")]
    partial class All
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rento.Entities.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DropOffBranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DropffDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PickupBranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PickupDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RentalRateId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("VehicleModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DropOffBranchId")
                        .IsUnique();

                    b.HasIndex("RentalRateId")
                        .IsUnique();

                    b.HasIndex("VehicleModelId")
                        .IsUnique();

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Rento.Entities.Entities.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CoordinatesLatitude")
                        .HasPrecision(15, 15)
                        .HasColumnType("decimal(15,15)");

                    b.Property<decimal>("CoordinatesLongitude")
                        .HasPrecision(15, 15)
                        .HasColumnType("decimal(15,15)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Branchs");
                });

            modelBuilder.Entity("Rento.Entities.Entities.BranchWorkingHour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("BranchWorkingHours");
                });

            modelBuilder.Entity("Rento.Entities.Entities.RentalRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RentalRateSchemasId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("VehicleCategorieId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RentalRateSchemasId")
                        .IsUnique();

                    b.ToTable("RentalRates");
                });

            modelBuilder.Entity("Rento.Entities.Entities.RentalRateSchema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DayRentFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DayRentTo")
                        .HasColumnType("date");

                    b.Property<int>("RentalName")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RentalRateSchemas");
                });

            modelBuilder.Entity("Rento.Entities.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("FuelTypes")
                        .HasColumnType("int");

                    b.Property<string>("LicensePlateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleManufacturerId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleModelId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("VehicleManufacturerId")
                        .IsUnique();

                    b.HasIndex("VehicleModelId")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Rento.Entities.Entities.VehicleCategorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VehicleCategories");
                });

            modelBuilder.Entity("Rento.Entities.Entities.VehicleManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VehicleManufacturers");
                });

            modelBuilder.Entity("Rento.Entities.Entities.VehicleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleCategorieId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleModelYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleCategorieId");

                    b.ToTable("VehicleModels");
                });

            modelBuilder.Entity("Rento.Entities.Entities.Booking", b =>
                {
                    b.HasOne("Rento.Entities.Entities.Branch", null)
                        .WithOne()
                        .HasForeignKey("Rento.Entities.Entities.Booking", "DropOffBranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rento.Entities.Entities.RentalRate", null)
                        .WithOne()
                        .HasForeignKey("Rento.Entities.Entities.Booking", "RentalRateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rento.Entities.Entities.VehicleModel", null)
                        .WithOne()
                        .HasForeignKey("Rento.Entities.Entities.Booking", "VehicleModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rento.Entities.Entities.BranchWorkingHour", b =>
                {
                    b.HasOne("Rento.Entities.Entities.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Rento.Entities.ValueObjects.WorkingHourIntervalValueObject", "Intervals", b1 =>
                        {
                            b1.Property<int>("BranchWorkingHourId")
                                .HasColumnType("int");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<int>("End")
                                .HasColumnType("int");

                            b1.Property<int>("Start")
                                .HasColumnType("int");

                            b1.HasKey("BranchWorkingHourId", "__synthesizedOrdinal");

                            b1.ToTable("BranchWorkingHours");

                            b1.ToJson("Intervals");

                            b1.WithOwner()
                                .HasForeignKey("BranchWorkingHourId");
                        });

                    b.Navigation("Intervals");
                });

            modelBuilder.Entity("Rento.Entities.Entities.RentalRate", b =>
                {
                    b.HasOne("Rento.Entities.Entities.RentalRateSchema", null)
                        .WithOne()
                        .HasForeignKey("Rento.Entities.Entities.RentalRate", "RentalRateSchemasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rento.Entities.Entities.Vehicle", b =>
                {
                    b.HasOne("Rento.Entities.Entities.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rento.Entities.Entities.VehicleManufacturer", null)
                        .WithOne()
                        .HasForeignKey("Rento.Entities.Entities.Vehicle", "VehicleManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rento.Entities.Entities.VehicleModel", null)
                        .WithOne()
                        .HasForeignKey("Rento.Entities.Entities.Vehicle", "VehicleModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rento.Entities.Entities.VehicleModel", b =>
                {
                    b.HasOne("Rento.Entities.Entities.VehicleCategorie", null)
                        .WithMany()
                        .HasForeignKey("VehicleCategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
