// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rento.Infrastructure.Implemenation.Db;

#nullable disable

namespace Rento.Migrations
{
    [DbContext(typeof(RentoDbContext))]
    partial class RentoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rento.Entities.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CoordinatesLatitude")
                        .HasPrecision(15, 15)
                        .HasColumnType("decimal(15,15)");

                    b.Property<decimal>("CoordinatesLongitude")
                        .HasPrecision(15, 15)
                        .HasColumnType("decimal(15,15)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Branchs");
                });

            modelBuilder.Entity("Rento.Entities.BranchWorkingHour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("BranchWorkingHours");
                });

            modelBuilder.Entity("Rento.Entities.BranchWorkingHour", b =>
                {
                    b.HasOne("Rento.Entities.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Rento.Entities.ValueObjects.WorkingHourIntervalValueObject", "Intervals", b1 =>
                        {
                            b1.Property<int>("BranchWorkingHourId")
                                .HasColumnType("int");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<int>("End")
                                .HasColumnType("int");

                            b1.Property<int>("Start")
                                .HasColumnType("int");

                            b1.HasKey("BranchWorkingHourId", "__synthesizedOrdinal");

                            b1.ToTable("BranchWorkingHours");

                            b1.ToJson("Intervals");

                            b1.WithOwner()
                                .HasForeignKey("BranchWorkingHourId");
                        });

                    b.Navigation("Intervals");
                });
#pragma warning restore 612, 618
        }
    }
}
